global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'inventory-api'
    static_configs:
      - targets: ['inventory-api:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s
